### ISSUE TITLE
Chrome extension does not work on certain websites

### ISSUE THREAD

**Issue by jigglycrumb** [jigglycrumb/ASCIImoji#2]
The chrome extension does not work on some websites. I'll try to collect these sites in this issue, so please comment below with the URL when you have found a site that is not already listed here.

There seems to be an issue with sites that use React. I guess the jQuery script doesn't really trigger updates to React's virtual DOM.

Sites that don't work:
- facebook.com
- twitch.tv

**Comment by Crazypkr1099** [comment]
Please get this working on twitch.tv and facebook.com... I would be so happy :o ʕ·͡ᴥ·ʔ﻿

**Comment by divy-work** [comment]
I hope this is still alive. WhatsappWeb and Instagram web interface also doesn't work. Both of them use React.

**Comment by hpcodecraft** [comment]
@divy-work I don't think jQuery is the problem, it is React. A React input often keeps its state/value and will insert it again with the next render. I've tried some things but I haven't found a way to trigger that React state update from the "outside world"

**Comment by jigglycrumb** [comment]
I discontinued the browser extension, therefore I'll close this issue.
