### ISSUE TITLE
Add Firefox support

### ISSUE THREAD

**Issue by ghost** [jigglycrumb/ASCIImoji#9]
There are a lot of people like me who love Firefox for its web development and privacy capabilities. It would be great if you could offer a port of ASCIImoji to Firefox. I've never done extension development before, but it sounds like porting it over isn't that difficult, [according to this documentation page](https://extensionworkshop.com/documentation/develop/porting-a-google-chrome-extension/) by mozilla. In fact, you can test your current extension compatibility by uploading your `.crx` extension file on [this page](https://www.extensiontest.com/).
I'd really like to see this coming to Firefox!

**Comment by jigglycrumb** [comment]
I have discontinued the Chrome extension, so I won't port it to Firefox myself. The code is still in the repository though, so if anyone is up for it, they can create a Firefox version.
